version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # 비밀번호 없이 실행 (보안 필요 시 변경)
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local
